### ISSUE TITLE
Save grades locally in the browser

### ISSUE THREAD

**Issue by HazemSamir** [HazemSamir/csed-gpa#2]
Save the [`years` array](https://github.com/HazemSamir/csed-gpa/blob/gh-pages/gpa-calculator.js#L13) in browser cache/cookies and load it at the beginning whenever the page loads later.

This should save the user the time to enter all his grades from the beginning every time.

Additional notes/features:
- The saved array may be saved/updated every time a change occurs, the function [`calculateGPA`](https://github.com/HazemSamir/csed-gpa/blob/gh-pages/gpa-calculator.js#L40) is called whenever a change occurs.
- An option maybe added to ask the user if he likes to save his grades or not.
- A button maybe added to reset grades and the cached array.

**Comment by Hamada14** [comment]
I have finished a working implementation for this issue, kindly check my pull request.

Although i didn't implement asking the user for his preference as i wasn't keen on adding unnecessary check boxes when the reset button exists.
